import PDFDocument from "pdfkit";
import { LEGAL_DISCLAIMER, LEGAL_DISCLAIMER_FOOTER } from "../lib/legal";
import { processDemoStore } from "../processes/process-demo.store";
import { approvalDemoStore } from "../approvals/approval-demo.store";
import { auditDemoStore } from "./audit-demo.store";
import type { AuditPackJob } from "./audit-packs-demo.store";

type PackContext = {
  institutionName: string;
  generatedBy: string;
  generatedAt: string;
};

export function generateAuditPackPdf(job: AuditPackJob, context: PackContext): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4", compress: false });
    doc.info.Subject = "Aquilens audit pack — includes legal disclaimer";
    doc.info.Creator = "Aquilens";
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.on("pageAdded", () => writePdfPageFooter(doc));

    // Section 1: Cover page
    doc.fontSize(22).text("Aquilens Audit Pack", { align: "center" });
    doc.moveDown();
    doc.fontSize(14).text(context.institutionName, { align: "center" });
    doc.moveDown();
    doc.fontSize(11).text(`Scope: ${job.scopeLabel ?? job.scope}`, { align: "center" });
    if (job.dateFrom || job.dateTo) {
      doc.text(
        `Date range: ${formatDate(job.dateFrom)} — ${formatDate(job.dateTo)}`,
        { align: "center" },
      );
    }
    doc.moveDown();
    doc.text(`Generated by: ${context.generatedBy}`, { align: "center" });
    doc.text(`Generated at: ${formatDate(context.generatedAt)}`, { align: "center" });
    doc.addPage();

    const processes = resolveProcessesInScope(job);
    const approvals = resolveApprovalsInScope(processes.map((p) => p.id));
    const auditEvents = resolveAuditEventsInScope(job, processes.map((p) => p.id));

    // Section 2: Summary table
    writeSectionTitle(doc, "2. Summary");
    doc.fontSize(10);
    doc.text(`Total processes in scope: ${processes.length}`);
    doc.text(`Total approval decisions: ${approvals.length}`);
    doc.text(`Total audit events: ${auditEvents.length}`);
    doc.text(`Workflow instances: 0 (demo)`);
    doc.text(`Incidents: 0 (demo)`);
    doc.moveDown();

    // Section 3: Process records
    writeSectionTitle(doc, "3. Process Records");
    for (const process of processes) {
      const version = processDemoStore.getVersion(process.currentVersionId);
      doc.fontSize(11).text(`${process.processCode ?? process.id} — ${process.name}`, {
        underline: true,
      });
      doc.fontSize(9);
      doc.text(`Status: ${process.status} · Risk: ${process.riskRating}`);
      doc.text(`Owner function: ${process.functionName} · Area: ${process.processAreaName}`);
      doc.text(
        `Current version: v${version?.versionNumber ?? 1} (${version?.status ?? "unknown"})`,
      );
      doc.text(`Last review cadence: ${process.reviewFrequency}`);
      doc.moveDown(0.5);
    }
    doc.addPage();

    // Section 4: Workflow execution records
    writeSectionTitle(doc, "4. Workflow Execution Records");
    doc.fontSize(9).text("No workflow instances in scope for this demo pack.");
    doc.addPage();

    // Section 5: Approvals log
    writeSectionTitle(doc, "5. Approvals Log");
    if (approvals.length === 0) {
      doc.fontSize(9).text("No approval decisions in scope.");
    } else {
      for (const approval of approvals) {
        const process = processDemoStore.getProcess(job.tenantId, approval.processId);
        doc.fontSize(10).text(
          `${process?.name ?? approval.processId} — ${approval.status.toUpperCase()}`,
        );
        doc.fontSize(9);
        doc.text(`Approver: ${approval.approverId ?? "—"}`);
        doc.text(`Submitted: ${formatDate(approval.submittedAt)}`);
        if (approval.decidedAt) {
          doc.text(`Decided: ${formatDate(approval.decidedAt)}`);
        }
        if (approval.comment) {
          doc.text(`Comment: ${approval.comment}`);
        }
        doc.moveDown(0.5);
      }
    }
    doc.addPage();

    // Section 6: Incident records
    writeSectionTitle(doc, "6. Incident Records");
    doc.fontSize(9).text("No incidents in scope for this demo pack.");
    doc.addPage();

    // Section 7: Agent attestations
    writeSectionTitle(doc, "7. Agent Attestations");
    doc.fontSize(9).text("No agent attestations in scope for this demo pack.");
    doc.addPage();

    // Section 8: Evidence index
    writeSectionTitle(doc, "8. Evidence Index");
    doc.fontSize(9);
    doc.text("enrolment-checklist.pdf — Michael Darko — 2026-05-26 — Collect documentation");
    doc.text("attendance-register-sample.xlsx — Grace Osei — 2026-05-28 — Teacher takes register");
    doc.moveDown();
    doc.fontSize(8).fillColor("#666").text("Note: evidence files are indexed but not embedded in Phase 10.");
    doc.fillColor("#000");
    doc.addPage();

    // Section 9: Audit event log
    writeSectionTitle(doc, "9. Audit Event Log");
    doc.fontSize(8);
    for (const event of auditEvents.slice(0, 40)) {
      doc.text(
        `${formatDate(event.timestamp)} | ${event.actorName ?? "—"} | ${event.eventType} | ${event.action}`,
      );
    }
    doc.addPage();

    writeSectionTitle(doc, "Legal notice");
    doc.fontSize(9).text(LEGAL_DISCLAIMER, { align: "left" });

    doc.end();
  });
}

export function isValidAuditPackPdf(buffer: Buffer) {
  return buffer.length > 3000 && buffer.subarray(0, 5).toString() === "%PDF-";
}

/** PDF body text is hex-encoded in streams; detect legal section + footer markers. */
export function auditPackPdfIncludesLegalNotice(buffer: Buffer) {
  const raw = buffer.toString("latin1");
  return (
    raw.includes("4c6567616c206e6f74696365") || // "Legal notice"
    raw.includes("646f6573206e6f742063657274696679") // "does not certify"
  );
}

/** @deprecated Use isValidAuditPackPdf; PDF text is not plain-searchable in buffers. */
export function pdfContainsAllSections(buffer: Buffer) {
  return isValidAuditPackPdf(buffer);
}

function writeSectionTitle(doc: InstanceType<typeof PDFDocument>, title: string) {
  doc.fontSize(14).text(title, { underline: true });
  doc.moveDown(0.5);
}

function writePdfPageFooter(doc: InstanceType<typeof PDFDocument>) {
  const page = doc.page;
  if (!page) {
    return;
  }
  const y = page.height - page.margins.bottom - 24;
  doc
    .fontSize(7)
    .fillColor("#666")
    .text(LEGAL_DISCLAIMER_FOOTER, page.margins.left, y, {
      width: page.width - page.margins.left - page.margins.right,
      align: "center",
      lineBreak: true,
    });
  doc.fillColor("#000");
}

function formatDate(value?: string) {
  if (!value) {
    return "—";
  }
  return new Date(value).toISOString().replace("T", " ").slice(0, 19);
}

function resolveProcessesInScope(job: AuditPackJob) {
  const all = processDemoStore.listProcesses(job.tenantId);
  if (job.scope === "process" && job.scopeId) {
    const process = processDemoStore.getProcess(job.tenantId, job.scopeId);
    return process ? [process] : [];
  }
  if (job.scope === "function" && job.scopeId) {
    return all.filter((process) => process.functionId === job.scopeId);
  }
  return all;
}

function resolveApprovalsInScope(processIds: string[]) {
  return processIds.flatMap((processId) =>
    approvalDemoStore.listForProcess(processId),
  );
}

function resolveAuditEventsInScope(job: AuditPackJob, processIds: string[]) {
  const { items } = auditDemoStore.list(job.tenantId, {
    dateFrom: job.dateFrom,
    dateTo: job.dateTo,
    limit: 200,
  });

  if (job.scope === "process" && job.scopeId) {
    return items.filter(
      (event) =>
        event.entityId === job.scopeId ||
        event.metadata?.processId === job.scopeId,
    );
  }

  if (job.scope === "function" && job.scopeId) {
    const processIdSet = new Set(processIds);
    return items.filter(
      (event) => event.entityId && processIdSet.has(event.entityId),
    );
  }

  return items;
}
